### ISSUE TITLE
Saran Bosque

### ISSUE THREAD

**Issue by dwiyudirayia** [IndomaximTechID/storaji#1]
Saran : 
1.Produk Detail / Pelanggan : Tambahkan fitur kita bisa melihat pelanggan / produk apa aja yang terinput pada tanggal 10 - 15 . Memakai jarak tanggal
2.Order : Multiple order .

Semoga bisa makin mantap lagi ~

**Comment by lowsprofile** [comment]
> 1.Produk Detail / Pelanggan : Tambahkan fitur kita bisa melihat pelanggan / produk apa aja yang terinput pada tanggal 10 - 15 . Memakai jarak tanggal

Added features on v1.0.0-beta.0 72046470f9fb4dea03a1bde6e781305102eb9d46, 2af3fb8eb849b880427ea7b2ceb3d0b32461ce6e and <code>[c537302](https://github.com/IndomaximTechID/storaji-ui/commit/c537302625e677387a7b0aac3d7d6420b0aa8cde)</code>

> 2.Order : Multiple order.

I will add this feature on v1.0.0 Release

**Comment by lowsprofile** [comment]
#2

**Comment by lowsprofile** [comment]
I will move the second request to this issue #2 and close this issue.
