### ISSUE TITLE
Some OS doesn't relaunch when do Install and Relaunch.

### ISSUE THREAD

**Issue by lowsprofile** [IndomaximTechID/storaji#11]
Related to https://github.com/IndomaximTechID/storaji/issues/9#issuecomment-358878689

**Comment by PrzemekSkw** [comment]
Now it's working great [update and relaunch]. Thanks :+1:

**Comment by lowsprofile** [comment]
@PrzemekSkw Ok, this is fixed then. Thanks for report it.
