### ISSUE TITLE
Difficult to find transaction specification

### ISSUE THREAD

**Issue by PrzemekSkw** [IndomaximTechID/storaji#13]
I have another request to make more easy to find transaction details. When I click in transactions I see only ID of transaction, client name and date. When I want to find product that I sell I must open every single transaction [click on ID] and search who buy required product. It will be great if You will add in transaction page also product name.

**Comment by lowsprofile** [comment]
So what you are really mean is, I need to add 1 column for product name in transaction table?

**Comment by lowsprofile** [comment]
If I didn't forgot, you can find it on reports > orders page. there you can filter by more options, and more columns too.

**Comment by PrzemekSkw** [comment]
@lowsprofile Yes, there's everything in reports tab, sory I don't check that :)

**Comment by lowsprofile** [comment]
Glad to hears that, I will close this then. :smiley:
