### ISSUE TITLE
DB error on install: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'image' can't have a default value

### ISSUE THREAD

**Issue by parq** [IndomaximTechID/storaji#15]
Hi,

I'm trying to test the app in a wamp server over win7.

The 1st issue I found was related to db estructure because of the support for utf8mb4 charset. To fix that I have to modify 'AppServiceProvider.php' as states in this guide (https://laravel.com/docs/master/migrations#creating-indexes):

use Illuminate\Support\Facades\Schema;
public function boot()
    {
        //
		Schema::defaultStringLength(191);
    }

But now I'm having problems with the migration. When I run 'php artisan migrate' get the following:

In PDOConnection.php line 79:

  SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'image' can't have a default value

In PDOConnection.php line 77:

  SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'image' can't have a default value

I was googling about that and found some settings in the db server, but after modify or comment out the 'sql_mode' lline, allways get the same error.

Any idea?

Regards...

**Comment by lowsprofile** [comment]
You should see this
https://github.com/IndomaximTechID/storaji/blob/461d631c6738a22970e726fe01327a15cac49869/database/migrations/2018_01_13_182222_add_image_to_product_table.php#L17

I have put default on image column, if you install it on mysql database. You should remove the default from it.

**Comment by parq** [comment]
It works!

>php artisan migrate
Migrating: 2018_01_13_182222_add_image_to_product_table
Migrated:  2018_01_13_182222_add_image_to_product_table

Tx!

**Comment by lowsprofile** [comment]
Glad to hears that :)
