### ISSUE TITLE
No Backup?

### ISSUE THREAD

**Issue by chope1** [IndomaximTechID/storaji#20]
Currently Using Windows version, please no backups and imports for the windows version?
Which database is ti using?

**Comment by lowsprofile** [comment]
Unfortunately this project is no longer maintained anymore until further notice.
You can request a backup database if you want, please email me at zdumb1885@outlook.com

**Comment by lowsprofile** [comment]
For now, just use private server. You can read documentation on [Development](https://github.com/IndomaximTechID/storaji#development) section how to install it.

**Comment by ergonomicus** [comment]
Maybe you could update readme file so everybody can see it is no longer maintained...

**Comment by lowsprofile** [comment]
@ergonomicus Thank you for reminding me, and I am sorry to you guys that I have to close this project.
