### ISSUE TITLE
[Meta] About Section - Website Link - Domain is Parked

### ISSUE THREAD

**Issue by jwshields** [IndomaximTechID/storaji#29]
Hello,

I realize this project is no longer maintained, but I wanted to make an issue here to mention that the URL for the project that is listed in the about section, `storaji.org` - this domain seems to be parked by some domain parking service, which, usually indicates that there is a number of redirects and risks run-ins with malware/viruses/etc.
I just wanted to post something here to raise awareness, and hopefully the link could be removed, so unsuspecting users don't accidentally risk a compromise/spam/malware/etc.  

I apologize for the pings, @eriestrisnadi @dwiyudirayia - but like I mentioned, I wanted to raise awareness; I hope this is not bothersome to you.
In any case, thank you in advance.

**Comment by eriestrisnadi** [comment]
Thank you @jwshields 
We have removed the domain in the about section.
