### ISSUE TITLE
Registration error in Windows version

### ISSUE THREAD

**Issue by downace** [IndomaximTechID/storaji#4]
Getting error "Email and password didn't match." when trying to register with existing email

There is an error in server response:
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'my-email' for key 'users_email_unique' (SQL: insert into `users` (`name`, `email`, `password`, `id`, `updated_at`, `created_at`) values (my-login, my-email, some-password-hash, some-id, 2017-12-27 00:11:15, 2017-12-27 00:11:15))"
```

_(some values are replaced)_

I think it should show something like "User already exists. Forgot password?"

**Comment by lowsprofile** [comment]
Yes, I was plan this on future release, notifications detail such as success and fail request for registration and login, thank you.

I will close this, and move it to #2. And if you want to help me with a PR I will take a look. 👍
