### ISSUE TITLE
Can you also share the electron build?

### ISSUE THREAD

**Issue by codeitlikemiley** [IndomaximTechID/storaji#5]

**Comment by lowsprofile** [comment]
Hi, thanks for taking an interest on Storaji. What's your exact mean? If you mean about the frontend repo you can visit at [IndomaximTechID/storaji-ui](https://github.com/IndomaximTechID/storaji-ui) in that repo you can find about the electron build conf, main, updater and the app source.

I think, I will add `CONTRIBUTING.md` file for contributors need. On that file I will explain about the (Frontend & Backend repo; How to contribute; Code style guides, etc)

**Comment by codeitlikemiley** [comment]
yup thats what im just looking for the electron app, where you can specify the build thanks

**Comment by codeitlikemiley** [comment]
do u have any milestone of the feature you want to add , so i can also check it , also i can help build some parts if needed

**Comment by lowsprofile** [comment]
>  where you can specify the build thanks

1. This is the resources for the app https://github.com/IndomaximTechID/storaji-ui/tree/master/build
2. This is the configuration for electron-builder https://github.com/IndomaximTechID/storaji-ui/blob/added4d756084d00f394d81b22335634c5a2f820/package.json#L12
3. This is the resources for electron such as (main.js, setupFrame.js, and releaseNote) https://github.com/IndomaximTechID/storaji-ui/tree/master/src/electron
4. To build on your machine first you need `yarn` globally, when done with clone the ui, run `yarn && yarn build --macos`



> do u have any milestone of the feature you want to add , so i can also check it , also i can help build some parts if needed

Please check this out [v1.0.0](https://github.com/IndomaximTechID/storaji-ui/milestone/3) for current milestone
I appreciated that you want to help me working on this, a PR would be great! If you help me a lot and want to join the organization I will invite you as a maintainer.

**Comment by lowsprofile** [comment]
I have updated readme, you can check [Development](https://github.com/IndomaximTechID/storaji/blob/master/readme.md#development) section.
