### ISSUE TITLE
Other currency.

### ISSUE THREAD

**Issue by PrzemekSkw** [IndomaximTechID/storaji#6]
Will be great if You add other currency (ex. PLN) and tax option (VAT - %). Great app, thanks.

**Comment by lowsprofile** [comment]
Thank you for the idea about another currency and tax option! It will be available on v1.0.0 Release, please be patient while we prepare another feature too. Added this issue to the milestone v1.0.0.

**Comment by PrzemekSkw** [comment]
Thanks, I can help to translate into polish language if You are interested.

**Comment by lowsprofile** [comment]
That will be great! I really appreciate if you come to help me with that.
For language that already on app located [here](https://github.com/IndomaximTechID/storaji-ui/tree/master/src/assets/i18n), Thanks again!! :smiley:

**Comment by lowsprofile** [comment]
Polish Language is available now, thanks for making it! Also, with the currency options.
Please update to v1.0.0-beta.7 related to this commit https://github.com/IndomaximTechID/storaji-ui/commit/f8259a2157660a93340f2a6915614fd05362a2b6

For tax options, still working on it. :)

**Comment by PrzemekSkw** [comment]
@lowsprofile You're great, thank You very much.
