### ISSUE TITLE
Does not play nicely when not connected to the Internet

### ISSUE THREAD

**Issue by probonopd** [IndomaximTechID/storaji#9]
Does not play nicely when not connected to the Internet:

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/1c73959cdfce810ce80873cdd8d137ca42516f5c/database/Storaji/screenshot.png)

Reference:
https://github.com/AppImage/appimage.github.io/pull/306

cc @develar

**Comment by lowsprofile** [comment]
@probonopd Since Storaji required an internet to access the data, it shouldn't work. But, this was give me an idea to add handler when starting the app to check if user has internet or not and show the dialog about it including 'Close' button. Thanks for reporting it!

**Comment by probonopd** [comment]
What is bothering me is that apparently it is the AppUpdater that crashes like this when there is no Internet connection. While it may be true for Storaji that it needs Internet anyway this is not necessarily true for other Electron apps that use the same updater. So this would best be fixed upstream in the updater component. Is it from https://github.com/electron-userland/electron-builder?

**Comment by PrzemekSkw** [comment]
@lowsprofile I want to make new thread but I see that @probonopd use app image. So I ask here: is appimages self-update or I have to use this: [https://github.com/AppImage/AppImageUpdate/releases/continuous](url) ?

**Comment by lowsprofile** [comment]
@probonopd Yes storaji use the same updater as Electron builder. But, I think it's from the storaji itself, which means storaji listen to the 'error' Event and show the error stack on dialog box. See https://github.com/IndomaximTechID/storaji-ui/blob/b574363caee109a22b95d3d7177648da3e138246/src/electron/setupFrame.js#L189

**Comment by lowsprofile** [comment]
@PrzemekSkw Storaji appimage use self-updater from https://www.electron.build/auto-update

**Comment by lowsprofile** [comment]
Fixed, now using file log for error. Update the app to v1.0.0-beta.6
https://github.com/IndomaximTechID/storaji-ui/commit/fd0096be5a21257b33184007ab41478c51c7b166

**Comment by PrzemekSkw** [comment]
@lowsprofile Today Storaji show me that there's update for download but when I click Yes nothing happen.

**Comment by lowsprofile** [comment]
@PrzemekSkw It may still downloading the updated app, dont close the app until it finish. When finish the app should notify you if the app has been downloaded and ready to install.

**Comment by PrzemekSkw** [comment]
@lowsprofile, I don't know that so I close app and download manualy :) I use Manjaro Deepin.

**Comment by PrzemekSkw** [comment]
@lowsprofile I try on my home laptop and it want to upgrade. I wait, then it popup that need to relaunch and app exit. That's it.

**Comment by lowsprofile** [comment]
>  I try on my home laptop and it want to upgrade. I wait, then it popup that need to relaunch and app exit.

@PrzemekSkw Yes, that was how Storaji updater works.

**Comment by PrzemekSkw** [comment]
@lowsprofile But it doesn't upgrade and don't run again when I click upgrade and relaunch.

**Comment by lowsprofile** [comment]
@PrzemekSkw Relating to this https://github.com/electron-userland/electron-builder/issues/2240#issuecomment-350304675, It was bug from an old version from the electron-updater. I will try to update electron-updater to the latest version. For now, please be patient and download manually. Thanks for the report! 👍

**Comment by PrzemekSkw** [comment]
@lowsprofile no problem, thanks for fast reply :)

**Comment by lowsprofile** [comment]
@PrzemekSkw I have updated the `electron-updater` to the latest version, please tell me if the **Install and Relaunch** didn't work too when next release is out. Thanks!!

**Comment by PrzemekSkw** [comment]
@lowsprofile I try on two Manjaro (gnome and deepin) laptops and still don't work. Maybe it's something with Manjaro appimages.

**Comment by lowsprofile** [comment]
@develar I have updated electron-updater since it couldn't install and relaunch related to the comment above but after updated to the latest its still doesn't work only on AppImage release, is the issue about this still on progress?

@probonopd or is AppImage couldn't do install and relaunch?

**Comment by probonopd** [comment]
> @probonopd or is AppImage couldn't do install and relaunch?

@lowsprofile if that is a feature of AppUpdater then I don't know since that is not an AppImage feature but an electron thing.

**Comment by lowsprofile** [comment]
@probonopd Ah, ok thanks. I will ask for help to electron team then.

Since it was out of topic, I will move the discussion about this to #11 and close this issue because this was already fixed like I said on https://github.com/IndomaximTechID/storaji/issues/9#issuecomment-358545910

Regards.

**Comment by probonopd** [comment]
Thank you, seems to be working now:

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/1b1999c1b4caf375d7d31ced1c11a12986e19695/database/Storaji/screenshot.png)

Reference:
https://github.com/AppImage/appimage.github.io/pull/341
